version: 2
sources:
  - name: aw
    database: fea24_4
    schema: raw_adventure_works
    tables:
      - name: salesorderdetail
        columns:
          - name: salesordderdetailid
            tests:
              - unique
              - not_null